name: LibGDX Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      JAVA_HOME: /opt/java/openjdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate LibGDX Project
        run: |
          chmod +x .github/scripts/create-libgdx-project.sh
          .github/scripts/create-libgdx-project.sh

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Desktop
        run: ./gradlew desktop:dist

      - name: Build Android APK
        run: ./gradlew android:assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/build/outputs/apk/debug/android-debug.apk

      - name: Upload Desktop JAR
        uses: actions/upload-artifact@v4
        with:
          name: desktop-jar
          path: desktop/build/libs/*.jar

      - name: Upload Project Structure (for inspection)
        uses: actions/upload-artifact@v4
        with:
          name: full-project-structure
          path: |
            android/
            core/
            desktop/
            gradlew*
            *.gradle
            gradle/
            settings.gradle