name: LibGDX Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Permissões para scripts
      run: chmod +x ./gradlew

    - name: Build do projeto
      run: ./gradlew clean build

    - name: Gerar APK debug
      run: ./gradlew android:assembleDebug

    - name: Gerar artefato ZIP do projeto
      run: zip -r projeto-libgdx.zip . -x '*.git*'

    - name: Salvar artefatos
      uses: actions/upload-artifact@v3
      with:
        name: projeto-libgdx
        path: projeto-libgdx.zip
